# Generated by Django 2.2.5 on 2020-11-11 09:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_coach', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='coach_pics')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('title', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Ass Manager', 'Ass Manager'), ('Gk Coach', 'GK Coach')], max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('trophies', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('games', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'coaches',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='player_pics')),
                ('position', models.CharField(choices=[('goal keeper', 'goal keeper'), ('defender', 'defender'), ('midfielder', 'midfielder'), ('forward', 'forward')], max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('available', models.BooleanField(default=True)),
                ('injured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('red_cards', models.IntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('has_contract', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='admin pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
            options={
                'verbose_name_plural': 'injuries',
            },
        ),
        migrations.CreateModel(
            name='Inaccessible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sold', 'sold'), ('terminated', 'terminated'), ('end contract', 'end contract')], max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('buyout_clause', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
            options={
                'verbose_name_plural': 'contracts ',
            },
        ),
        migrations.CreateModel(
            name='CoachContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Coach')),
            ],
        ),
    ]
