# Generated by Django 2.2.5 on 2020-07-06 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('image', models.ImageField(default='default.jpg', upload_to='player_pics')),
                ('position', models.CharField(choices=[('gk', 'gk'), ('defender', 'defender'), ('mid', 'mid'), ('forward', 'forward')], max_length=200)),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('jersey_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('red_cards', models.IntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('has_contract', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
