# Generated by Django 2.2.5 on 2020-11-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201111_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerjersey',
            name='no',
            field=models.IntegerField(),
        ),
    ]
