# Generated by Django 2.2.5 on 2020-07-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'coaches'},
        ),
    ]
