# Generated by Django 2.2.5 on 2020-11-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201112_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerjersey',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PlayerJersey'),
        ),
    ]
