# Generated by Django 2.2.5 on 2020-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201112_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerjersey',
            name='no',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17)]),
        ),
    ]
