# Generated by Django 2.2.5 on 2020-11-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201114_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='salary',
            new_name='daily_pay',
        ),
    ]
