# Generated by Django 2.2.5 on 2020-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercontract',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
