# Generated by Django 2.2.5 on 2020-07-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_playercontract_remaining_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercontract',
            name='remaining_days',
        ),
    ]
