# Generated by Django 2.2.5 on 2020-09-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200907_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'contracts '},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='total_salary',
        ),
    ]
