# Generated by Django 2.2.5 on 2020-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200907_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
