# Generated by Django 2.2.5 on 2020-10-25 15:14

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_player_clean_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
