# Generated by Django 2.2.5 on 2020-10-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0001_initial'),
        ('main', '0013_player_clean_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='injury.Injury'),
        ),
    ]
