# Generated by Django 2.2.5 on 2020-10-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_player_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='injury',
        ),
    ]
