# Generated by Django 2.2.5 on 2020-10-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_player_injury'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='country',
        ),
    ]
