# Generated by Django 2.2.5 on 2020-10-26 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
