# Generated by Django 2.2.5 on 2020-10-09 12:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201009_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
