# Generated by Django 2.2.5 on 2020-10-26 09:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_injury_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
