# Generated by Django 2.2.5 on 2020-10-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201026_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Coach')),
            ],
        ),
    ]
