# Generated by Django 2.2.5 on 2020-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_coachcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.BooleanField(default=False),
        ),
    ]
