# Generated by Django 2.2.5 on 2020-10-28 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_player_injured'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sold', 'sold'), ('terminated', 'terminated'), ('end contract', 'end contract')], max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
        ),
    ]
