# Generated by Django 2.2.5 on 2020-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201030_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='admin pictures')),
            ],
        ),
    ]
