# Generated by Django 2.2.5 on 2020-10-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_adminpictures_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPictures',
            new_name='Picture',
        ),
    ]
