# Generated by Django 2.2.5 on 2020-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201105_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goal keeper', 'goal keeper'), ('defender', 'defender'), ('midfielder', 'midfielder'), ('forward', 'forward')], max_length=200),
        ),
    ]
