# Generated by Django 2.2.5 on 2020-10-07 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('injury_id', models.AutoField(primary_key=True, serialize=False)),
                ('injury_type', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('players', models.CharField(blank=True, editable=False, max_length=50)),
                ('check_in_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_edited_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('injury', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='injury.Injury')),
            ],
        ),
    ]
