# Generated by Django 2.2.5 on 2020-10-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0002_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='check_in',
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
