# Generated by Django 2.2.5 on 2020-10-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0004_auto_20201009_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injury',
            options={'verbose_name_plural': 'injuries'},
        ),
    ]
