# Generated by Django 2.2.5 on 2020-10-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_player_injury'),
        ('injury', '0006_remove_injury_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Injury',
        ),
    ]
