# Generated by Django 2.2.5 on 2020-10-09 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0015_remove_player_injury'),
        ('injury', '0007_delete_injury'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInjury',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('injury_type', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ManyToManyField(to='main.Player')),
            ],
        ),
    ]
