# Generated by Django 2.2.5 on 2020-10-09 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_player_injury'),
        ('injury', '0008_playerinjury'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('injury_type', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
            ],
            options={
                'verbose_name_plural': 'injuries',
            },
        ),
        migrations.DeleteModel(
            name='PlayerInjury',
        ),
        migrations.AddField(
            model_name='checkout',
            name='injury',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='injury.Injury'),
        ),
    ]
