# Generated by Django 2.2.5 on 2020-10-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0009_auto_20201009_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
