# Generated by Django 2.2.5 on 2020-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20200721_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='club',
            field=models.CharField(default='Thucheiz United', max_length=200),
        ),
    ]
