# Generated by Django 2.2.5 on 2020-10-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_auto_20200721_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='opponent_image',
            new_name='image',
        ),
    ]
