# Generated by Django 2.2.5 on 2020-10-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0018_coachcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coach', models.ManyToManyField(blank=True, null=True, to='main.Coach')),
                ('player', models.ManyToManyField(blank=True, null=True, to='main.Player')),
            ],
        ),
    ]
