# Generated by Django 2.2.5 on 2020-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
