# Generated by Django 2.2.5 on 2020-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=200, null=True),
        ),
    ]
