# Generated by Django 2.2.5 on 2020-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='coach',
            field=models.ManyToManyField(to='main.Coach'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='player',
            field=models.ManyToManyField(to='main.Player'),
        ),
    ]
