# Generated by Django 2.2.5 on 2020-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201027_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='coach',
            field=models.ManyToManyField(blank=True, to='main.Coach'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='player',
            field=models.ManyToManyField(blank=True, to='main.Player'),
        ),
    ]
